apiVersion: v1
kind: ConfigMap
metadata:
  name: ex288-config
data:
  msg: "hello-from-configmap"
---
apiVersion: v1
kind: Secret
metadata:
  name: ex288-secret
type: Opaque
stringData:
  token: "dev-token"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ex288-pvc
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests: { storage: 1Gi }
  storageClassName: crc-csi-hostpath-provisioner
